name: Run Tests daily on latest gradle versions
on:
  schedule:
    - cron: 0 0 * * * # daily
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
        gradle-version: [4.9, current, rc] # Builds against 4.9, the current release version and the release candidate of gradle
        java-version: [1.8, 11, 14]
        exclude:
          - java-version: 14
            gradle-version: 4.9
          - java-version: 11
            gradle-version: 4.9
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ matrix.gradle-version }}
          arguments: check build test --stacktrace